### ISSUE TITLE
Error when compiling on Ubuntu 16.04 with OpenCV 3.3.1

### ISSUE THREAD

**Issue by esimkowitz** [h3ct0r/fast_ellipse_detector#1]
I am trying to get your sample code to work and I've spun up a system with Ubuntu 16.04 and OpenCV 3.3.1 but I am getting compiler errors. What version of OpenCV did you use?

**Comment by esimkowitz** [comment]
Update: It looks like the specific error is that it is unable to locate the function `ellipse()` as used in common.h and main.cpp. I wasn't able to find this function defined in your source code. Where do you define this function/what library is it from?

**Comment by esimkowitz** [comment]
for those running into this in the future, it works with OpenCV 2.4.13 as long as that's the only OpenCV you have installed. I'm working on improved documentation/usability for this in my fork of this repo and I'll make a PR when I'm done

**Comment by vgg4resnet** [comment]
I am facing the same issue ， how do u solve it，any way to use the newest opencv？

**Comment by vgg4resnet** [comment]
I solved  by adding #include <opencv2/opencv.hpp> to common.h
